### ISSUE TITLE
一直报找不到dSYM文件

### ISSUE THREAD

**Issue by WeMadeCode** [zqqf16/SYM#14]
企业包，dSYM 和 ips文件在一个目录。一直报 找不到dSYM文件错误

**Comment by zqqf16** [comment]
@WeMadeCode 试一下 `mdfind "com_apple_xcode_dsym_uuids == *"` 这个命令，看输出结果里有没有你的dSYM文件。

**Comment by WeMadeCode** [comment]
@zqqf16 试了 有我的 dSYM 文件

**Comment by zqqf16** [comment]
@WeMadeCode UUID 能对上吗？方便的话可否贴一下 crash 源文件，以及`mdfind "com_apple_xcode_dsym_uuids == *"`的输出结果？
