### ISSUE TITLE
解析之后依旧是友盟的日志

### ISSUE THREAD

**Issue by zxiang2013** [zqqf16/SYM#16]
找不到dSYM，都不支持上传的吗?没有dSYM怎么符号化？

**Comment by zqqf16** [comment]
@zxiang2013 dSYM文件需要事先保存到本地，或者用自定义的dSYM下载脚本去打包服务器上拉取。

**Comment by zxiang2013** [comment]
- 是您这个app没有上传dSYM 的地方🫣> @zxiang2013 dSYM文件需要事先保存到本地，或者用自定义的dSYM下载脚本去打包服务器上拉取。

**Comment by zqqf16** [comment]
@zxiang2013 SYM是一个本地符号化的工具，可以理解为一个图形化的atos工具，不存在“上传dSYM”这个概念

**Comment by zxiang2013** [comment]
我的意思是符号化需要dSYM文件，但是SYM没有地方支持加入dSYM
<img width="802" alt="image" src="https://user-images.githubusercontent.com/5276499/159203927-89efb1b8-0152-460a-a3a5-8faeaaa5eb1b.png">
shi是我理解错了吗？: D

**Comment by zqqf16** [comment]
@zxiang2013  点击“没有找到dSYM文件”按钮，再点击“显示dSYM信息“，里面有”导入“的选项，藏得太深了😂

不过话又说回来，如果dSYM文件在本机磁盘上，这里应该会自动索引到，不需要手动导入。

**Comment by zxiang2013** [comment]
我知道可以自动搜索，但是我的这个比较特殊，不在默认路径。所以没找到。但是我点击显示dSYM，没有导入按钮啊🔘

**Comment by zxiang2013** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/5276499/159256324-6516e082-fb51-43a7-b011-e6afead3fd89.png">

**Comment by zqqf16** [comment]
crash 信息解析失败了，方便贴一下原始日志不？

**Comment by zxiang2013** [comment]
*** -[NSMutableIndexSet addIndexesInRange:]: Range {9223372036854775807, 1} exceeds maximum index value of NSNotFound - 1
(null)
((
	0   CoreFoundation                      0x000000018d3ae5c8 58500388-BF36-397C-84CF-17315A3445B6 + 1217992
	1   libobjc.A.dylib                     0x00000001a1e2d7a8 objc_exception_throw + 60
	2   Foundation                          0x000000018e61dd08 63D26DEE-A1FB-34B0-9ADA-CC52E7F1D60C + 146696
	3   UIKitCore                           0x000000018fd13888 186C18FD-1082-3811-A761-88E8376C7E69 + 11856008
	4   UIKitCore                           0x000000018fd1b43c 186C18FD-1082-3811-A761-88E8376C7E69 + 11887676
	5   Education                           0x0000000105096710 Education + 1894160
	6   UIKitCore                           0x000000018fd1ac2c 186C18FD-1082-3811-A761-88E8376C7E69 + 11885612
	7   UIKitCore                           0x000000018fd154f0 186C18FD-1082-3811-A761-88E8376C7E69 + 11863280
	8   UIKitCore                           0x000000018fd1574c 186C18FD-1082-3811-A761-88E8376C7E69 + 11863884
	9   UIKitCore                           0x0000000190261e10 186C18FD-1082-3811-A761-88E8376C7E69 + 17419792
	10  UIKitCore                           0x000000019025c654 186C18FD-1082-3811-A761-88E8376C7E69 + 17397332
	11  UIKitCore                           0x000000018ffb0078 186C18FD-1082-3811-A761-88E8376C7E69 + 14594168
	12  UIKitCore                           0x0000000190253410 186C18FD-1082-3811-A761-88E8376C7E69 + 17359888
	13  UIKitCore                           0x00000001902526e0 186C18FD-1082-3811-A761-88E8376C7E69 + 17356512
	14  UIKitCore                           0x000000019025368c 186C18FD-1082-3811-A761-88E8376C7E69 + 17360524
	15  QuartzCore                          0x0000000190604eb8 B5B69CA2-65B2-359F-BCFF-24FD57D1EBF7 + 85688
	16  QuartzCore                          0x00000001906e3eb8 B5B69CA2-65B2-359F-BCFF-24FD57D1EBF7 + 999096
	17  CoreFoundation                      0x000000018d3038bc 58500388-BF36-397C-84CF-17315A3445B6 + 518332
	18  CoreFoundation                      0x000000018d3290d4 58500388-BF36-397C-84CF-17315A3445B6 + 671956
	19  CoreFoundation                      0x000000018d328454 58500388-BF36-397C-84CF-17315A3445B6 + 668756
	20  CoreFoundation                      0x000000018d322038 58500388-BF36-397C-84CF-17315A3445B6 + 643128
	21  CoreFoundation                      0x000000018d3211c0 CFRunLoopRunSpecific + 600
	22  GraphicsServices                    0x00000001a4909734 GSEventRunModal + 164
	23  UIKitCore                           0x000000018fd8f7e4 186C18FD-1082-3811-A761-88E8376C7E69 + 12363748
	24  UIKitCore                           0x000000018fd95054 UIApplicationMain + 168
	25  Education                           0x0000000105480df4 Education + 6000116
	26  libdyld.dylib                       0x000000018cfddcf8 B08AB7C2-64E8-3937-9487-C33D0175FD34 + 7416
)

dSYM UUID: BCB0E714-B749-3185-82D0-94F8B6AC430A
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: Education
Base Address: 0x0000000104ec8000

**Comment by zqqf16** [comment]
找到原因了，解析 Umeng 日志的时候把 binary image 弄丢了，发布了新版本来解决这个问题，可以试一下 https://github.com/zqqf16/SYM/releases/download/v0.8.5/SYM_0.8.5_95.dmg

**Comment by zxiang2013** [comment]
嗯，新版本是可以查找dSYM了，但是符号化之后还是找不出问题所在，【手动笑哭】

**Comment by zqqf16** [comment]
大概率是UUID没对上，建议检查一下dSYM文件的UUID，看看跟crash log里面的是否一致～

**Comment by zxiang2013** [comment]
不是UUID的问题 :|

**Comment by zqqf16** [comment]
😂那方便再贴一下 dSYM 文件吗，我排查一下，文件如果太大可以发我邮箱：zqqf16[at]gmail.com
