### ISSUE TITLE
下载地址有问题，下载不下来

### ISSUE THREAD

**Issue by houjianzheng** [zqqf16/SYM#19]
https://github.com/zqqf16/SYM/releases/download/v0.8.7/SYM_0.8.7_104.dmg

**Comment by zqqf16** [comment]
网络问题吧，我这儿是好的

**Comment by zqqf16** [comment]
更新了一个新版本：https://github.com/zqqf16/SYM/releases/download/v0.8.8/SYM_0.8.8_106.dmg
