### ISSUE TITLE
Monospace font issue

### ISSUE THREAD

**Issue by tdimeco** [zqqf16/SYM#4]
Hi,

First, thanks for your very useful tool!

I think there is a bug regarding the font used by the crash log viewer. If I open the .ips file from the Finder, the font used by the crash log viewer is monospaced, that's perfect. But if I drag and drop the .ips file into the app directly, the font changes to a default non-monospaced font (and it's less readable).

Double-clic from Finder:

<img width="912" alt="finder" src="https://user-images.githubusercontent.com/3112087/43089724-b3fb93f8-8ea5-11e8-808a-bce0d4dade09.png">

Drag-and-drop:

<img width="912" alt="dragndrop" src="https://user-images.githubusercontent.com/3112087/43089736-bb42193e-8ea5-11e8-80a4-d2beb19e35b2.png">

Thanks!

Thomas

**Comment by zqqf16** [comment]
Hi @tdimeco 

Thanks for your feedback.
This issue has been fixed in [3ad46b565474d180ee991915ffd91976a555d31e](https://github.com/zqqf16/SYM/commit/3ad46b565474d180ee991915ffd91976a555d31e).

Please try [v0.4.4](https://github.com/zqqf16/SYM/releases/tag/v0.4.4) 😁

**Comment by tdimeco** [comment]
Cool! Thanks 😊
