### ISSUE TITLE
友盟格式的日志解析系统符号表

### ISSUE THREAD

**Issue by ryansong** [zqqf16/SYM#7]
友盟的错误日志(从剪贴板复制)好像是无法正确解析. 
本意是为了解析系统的符号表, 但发现使用这个工具无法正常解析友盟的日志(程序的日志在友盟上是可以正确解析, 符号表友盟不支持).

**Comment by zqqf16** [comment]
友盟的日志把系统库的 uuid、加载地址等信息都丢了，解不出来
